idf_component_register(
    SRCS
        "main.c"
        "sd.c"
        "audio.c"
        "ui.c"
        "io.c"
        "player.c"
        "cli.c"
        "fonts/mp3_inter_12.c"
        "fonts/mp3_inter_14.c"
        "fonts/mp3_inter_18.c"
    INCLUDE_DIRS "." "fonts"
    REQUIRES
        driver
        esp_lcd
        esp_adc
        esp_timer
        fatfs
        sdmmc
        nvs_flash
)
